# Site settings
title: "Ohara's Atelier"
SEOTitle: "Christopher O’Hara | Ohara's Atelier"
header-img: "img/m4-c.jpg"
email: "ohara124c41@gmail.com"
description: "AI System Architect | Space & Robotics | Digital Twins, RL under constraints, and resilient cyber-physical systems."
keyword: "Christopher Ohara, System Architecture, Systems Engineering, Space Engineering, Robotics, AI, Digital Twin, Generative Engineering"
url: "https://ohara124c41.github.io"    # your host, for absolute URL
baseurl: ""                             # e.g., '/blog' if hosted at 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# Social
RSS: false
github_username:    "ohara124c41"
facebook_username:  "oharainternational"
linkedin_username:  "ohara124c41"

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  - "less"
  - "node_modules"
  - "Gruntfile.js"
  - "package.json"
  - "README.md"
  - "README.zh.md"
anchorjs: true
timezone: "America/Los_Angeles"

# Plugins (GitHub Pages–supported)
plugins:
  - jekyll-paginate

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax        # Enable LaTeX rendering (requires MathJax script in layout)
  math_engine_opts: {}        # Config provided via layout script tag
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Comments / Analytics (disabled by default)
# disqus_username: your-disqus-shortname
# ga_tracking: ""            # e.g., G-XXXXXXXXXX (GA4)
# ga_tracking_anonymize_ip: true

giscus:
  enable: true
  repo: Ohara124c41/Ohara124c41.github.io
  repo_id: MDEwOlJlcG9zaXRvcnkxMzgwNjgwMDQ=
  category: General
  category_id: DIC_kwDOCDrAJM4Cvxa4
  mapping: pathname
  reactions: 1
  emit_metadata: 0
  input_position: bottom
  theme: preferred_color_scheme   # auto-switch with user theme
  lang: en


# Sidebar settings
sidebar: true
sidebar-about-description: "For the next quantum leap"
sidebar-avatar: "/img/avatar-ohara.jpg"  # update to an existing image path in your repo

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering flag used by some themes/layouts (safe to keep true)
page-mathjax: true
